name: change-demo-1

on:
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: Approve Change Request in ServiceNow
      shell: bash
      run : echo "Build Completed...."
    
  approveChangeRequest:
    name: 'Approve Change Request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: ServiceNow Change
      uses: ServiceNow/servicenow-devops-change@v1.34.2
      with:
        devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
        devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
        instance-url: ${{ secrets.SN_INSTANCE_URL }}
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        context-github: ${{ toJSON(github) }}
        job-name: 'Approve Change Request'
        change-request: '{"setCloseCode":"false","attributes":{"short_description":"Application deployment for samples-dev","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
        interval: '100'
        timeout: '3600'

  eploy:
    name: 'Deploy'
    needs: approveChangeRequest
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Target
      shell: bash
      run : echo "Deployment Started...."
