name: sonarsetup

on:
  push:
    branches:
      - workflow
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_DEV_NAME: samples-app-dev    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use
  GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  SONAR_ORG_KEY: ${{ secrets.SONAR_ORG_KEY }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: samples-app/package-lock.json

    - name: npm install.
      run: npm install
      working-directory: ./samples-app
     
    - name: sonarqube-scanner install.
      run: npm install -g sonarqube-scanner

    - name: npm build.
      run: npm run clean && npm run build --if-present
      working-directory: ./samples-app
    
    - name: npm test.
      run: npm run test --if-present
      working-directory: ./samples-app
      
    - name: convert to junit xml
      run: npm run junitxml
      working-directory: ./samples-app
    
    - name: Wait for few secs
      uses: jakejarvis/wait-action@master
      with:
          time: '600s'
